export { default as Alert } from './alert/Alert.vue'
export { default as NavBar } from './navbar/NavBar.vue'
export { default as ActiveFriend } from './chat/ActiveFriend.vue'
export { default as Friends } from './chat/Friends.vue'
export { default as UserAvatar } from './chat/UserAvatar.vue'
export { default as UserBadge } from './chat/UserBadge.vue'
